### ISSUE TITLE
Resource Group Tags

### ISSUE THREAD

**Issue by chtwilfer** [PieterbasNagengast/Azure-HubSpoke-LabBuilder#9]
During deployment, the resource tags are not set for the resource groups.

For completion and due to possible Azure policies, resource group tags are definitely of interest.

**Comment by PieterbasNagengast** [comment]
Fixed! you can now set Tags all resource types including resource groups.

gr,
pb

**Comment by chtwilfer** [comment]
very nice, what you are doing. thx for that.
